include: package:lint/analysis_options.yaml

linter:
  rules:
    always_use_package_imports: true
    avoid_classes_with_only_static_members: false
    avoid_positional_boolean_parameters: false
    constant_identifier_names: false
    prefer_single_quotes: true
