name: gestionuh
description: A UH managment app

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  dio: ^4.0.0
  flash: ^1.5.1
  fl_chart: ^0.35.0
  flutter:
    sdk: flutter
  flutter_bloc: ^7.0.0
  flutter_secure_storage: ^4.1.0
  get_it: ^6.0.0
  json_annotation: ^4.0.1
  shared_preferences: ^2.0.5
  url_launcher: ^6.0.3

dev_dependencies:
  build_runner: ^1.12.2
  flutter_launcher_icons: ^0.9.0
  flutter_native_splash: ^1.1.7+1
  json_serializable: ^4.1.0

  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/

flutter_native_splash:
  image: assets/images/splash2.png
  color: "#5b0101"
  fill: false

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/ico.png"
