name: gestionuh
description: A UH managment app

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^6.1.0
  json_annotation: ^3.1.1
  get_it: ^5.0.0
  flutter_secure_storage: ^3.3.5
  shared_preferences: ^0.5.6
  dio: ^3.0.10
  url_launcher: ^5.7.10
  fl_chart: ^0.35.0
  flash: ^1.3.1
  cupertino_icons: ^1.0.0

dev_dependencies:
  json_serializable: ^3.5.1
  build_runner: ^1.11.1
  flutter_native_splash: ^0.3.0
  flutter_launcher_icons: ^0.8.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/

flutter_native_splash:
  image: assets/images/splash2.png
  color: "#5b0101"
  fill: false

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/ico.png"
