name: gestionuh
description: Aplicación para la gestión electrónica en la Universidad de La Habana.

publish_to: 'none'

version: 1.1.0+4

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  collection: ^1.15.0-nullsafety.4
  cupertino_icons: ^1.0.2
  dio: ^4.0.0
  flash: ^1.5.1
  flutter:
    sdk: flutter
  flutter_bloc: ^7.0.0
  flutter_localizations:
    sdk: flutter
  flutter_secure_storage: ^4.1.0
  flutter_web_plugins:
    sdk: flutter
  freezed_annotation: ^0.14.1
  get_it: ^6.1.1
  json_annotation: ^4.0.1
  package_info_plus: ^1.0.0
  page_transition: ^2.0.1-nullsafety.0
  responsive_builder: ^0.4.1
  shared_preferences: ^2.0.5
  syncfusion_flutter_charts: ^19.1.57+1
  url_launcher: ^6.0.3

dev_dependencies:
  build_runner: ^2.0.1
  flutter_launcher_icons: ^0.9.0
  flutter_native_splash: ^1.1.8+4
  flutter_test:
    sdk: flutter
  freezed: ^0.14.1+3
  json_serializable: ^4.1.1
  lint: ^1.5.3

flutter:
  uses-material-design: true
  assets:
    - assets/images/

flutter_native_splash:
  image: assets/images/splash2.png
  color: '#fdfdfd'
  fill: false

flutter_icons:
  android: 'launcher_icon'
  ios: true
  image_path: 'assets/images/icon.png'
