const LOGIN_ROUTE_NAME = '/login';
const REGISTER_ROUTE_NAME = '/register';
const HOME_ROUTE_NAME = '/';
const RECOVER_PASSWORD_ROUTE_NAME = '/recover-password';
// const QUOTA_ROUTE_NAME = '/quota';
// const PROFILE_ROUTE_NAME = '/profile';
// const MAIL_ROUTE_NAME = '/mail';
// const RESET_PASSWORD_ROUTE_NAME = '/reset-password';
// const ABOUT_ROUTE_NAME = '/about';
