name: deploy
on:
  push:
    branches: [ master ]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1
        with:
          channel: stable
      - run: flutter pub get
      - run: flutter format --set-exit-if-changed .
      - run: flutter analyze --fatal-infos
      - run: flutter test
      - uses: erickzanardo/flutter-gh-pages@v2
